ejxzhn22/itjunior

src/main/java/com/spring/itjunior/controller/FreeBoardController.java
src/main/java/com/spring/itjunior/mapper/FreeBoardMapper.java
src/main/java/com/spring/itjunior/service/FreeBoardService.java
src/main/resources/application.yml
src/main/resources/mapper/FreeBoardMapper.xml
src/test/java/com/spring/itjunior/service/FreeBoardServiceTest.java

freeBoard 모든 게시글가져오기, 게시글 추가 테스트 완료

freeBoard 모든 게시글가져오기, 게시글 추가 테스트 완료

---

src/main/java/com/spring/itjunior/controller/FreeBoardController.java
src/main/java/com/spring/itjunior/mapper/FreeBoardMapper.java
src/main/java/com/spring/itjunior/service/FreeBoardService.java
src/main/resources/mapper/FreeBoardMapper.xml
src/main/webapp/WEB-INF/views/freeBoard/freeBoard.jsp
src/main/webapp/WEB-INF/views/freeBoard/freeBoardDetail.jsp
src/main/webapp/WEB-INF/views/freeBoard/freeBoardForm.jsp
src/test/java/com/spring/itjunior/service/FreeBoardServiceTest.java

게시판 리스트, 글상세, 글쓰기 폼

---

build.gradle
src/main/java/com/spring/itjunior/config/SecurityConfig.java
src/main/java/com/spring/itjunior/controller/MemberController.java
src/main/java/com/spring/itjunior/domain/Member.java
src/main/java/com/spring/itjunior/exception/CommonExceptionHandler.java
src/main/java/com/spring/itjunior/mapper/MemberMapper.java
src/main/java/com/spring/itjunior/service/ApiService.java
src/main/java/com/spring/itjunior/service/MemberService.java
src/main/java/com/spring/itjunior/service/MemberServiceImpl.java
src/main/java/com/spring/itjunior/service/RecruitServiceImpl.java
src/main/resources/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/home.jsp
src/main/webapp/WEB-INF/views/member/joinForm.jsp
src/main/webapp/WEB-INF/views/member/loginForm.jsp
src/test/java/com/spring/itjunior/member/MemberTests.java

Jaebokmember

---

src/main/java/com/spring/itjunior/config/SecurityConfig.java
src/main/java/com/spring/itjunior/controller/FreeBoardController.java
src/main/java/com/spring/itjunior/domain/FreeBoard.java
src/main/java/com/spring/itjunior/domain/FreeLike.java
src/main/java/com/spring/itjunior/dto/BoardDto.java
src/main/java/com/spring/itjunior/mapper/FreeBoardMapper.java
src/main/java/com/spring/itjunior/service/FreeBoardService.java
src/main/resources/mapper/FreeBoardMapper.xml
src/main/resources/static/js/freeBoard.js
src/main/webapp/WEB-INF/views/freeBoard/freeBoardDetail.jsp
src/main/webapp/WEB-INF/views/freeBoard/freeBoardForm.jsp

글상세, 조회수, 추천수

---

.gitignore
src/main/java/com/spring/itjunior/config/SecurityConfig.java
src/main/java/com/spring/itjunior/config/auth/PrincipalDetails.java
src/main/java/com/spring/itjunior/controller/MemberController.java
src/main/java/com/spring/itjunior/domain/FreeBoard.java
src/main/java/com/spring/itjunior/exception/CommonExceptionHandler.java
src/main/java/com/spring/itjunior/service/MemberServiceImpl.java
src/main/resources/application.yml
src/main/webapp/WEB-INF/views/home.jsp
src/main/webapp/WEB-INF/views/member/loginForm.jsp
src/test/java/com/spring/itjunior/BCcyptEncoder/EncoderTests.java
src/test/java/com/spring/itjunior/member/MemberTests.java

시큐리티 구현중 머지 하겠습니다.. js폴더루트 사용 가능 로그인 user로 가능

Memberfinal

---

src/main/java/com/spring/itjunior/config/SecurityConfig.java
src/main/java/com/spring/itjunior/config/auth/PrincipalDetails.java
src/main/java/com/spring/itjunior/config/auth/PrincipalDetailsService.java
src/main/java/com/spring/itjunior/controller/FreeBoardController.java
src/main/java/com/spring/itjunior/controller/HomeController.java
src/main/java/com/spring/itjunior/service/MemberService.java
src/main/java/com/spring/itjunior/service/MemberServiceImpl.java
src/main/webapp/WEB-INF/views/layout/footer.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp

spring security 구현중,, jsp로 가져오기 전단계까지 완료

---

src/main/java/com/spring/itjunior/controller/FreeBoardController.java
src/main/java/com/spring/itjunior/dto/BoardDto.java
src/main/java/com/spring/itjunior/mapper/FreeBoardMapper.java
src/main/java/com/spring/itjunior/service/FreeBoardService.java
src/main/resources/application.yml
src/main/resources/mapper/FreeBoardMapper.xml
src/main/webapp/WEB-INF/views/freeBoard/freeBoard.jsp
src/main/webapp/WEB-INF/views/freeBoard/freeBoardDetail.jsp
src/main/webapp/WEB-INF/views/freeBoard/freeBoardUpdateForm.jsp

게시글 수정, 삭제, 댓글 폼 , 추천수

---

src/main/java/com/spring/itjunior/config/auth/PrincipalDetails.java
src/main/java/com/spring/itjunior/controller/FreeBoardController.java
src/main/java/com/spring/itjunior/service/FreeBoardService.java
src/main/resources/static/js/freeBoard.js
src/main/webapp/WEB-INF/views/freeBoard/freeBoardDetail.jsp
src/main/webapp/WEB-INF/views/freeBoard/freeBoardUpdateForm.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp

회원추가, 게시글 작성 수정 추천 확인

---

src/main/java/com/spring/itjunior/controller/MemberApiController.java
src/main/java/com/spring/itjunior/controller/MemberController.java
src/main/java/com/spring/itjunior/domain/Member.java
src/main/java/com/spring/itjunior/service/MemberServiceImpl.java
src/main/resources/application.yml
src/main/resources/mapper/MemberMapper.xml
src/main/resources/static/js/freeBoard.js
src/main/webapp/WEB-INF/views/home.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp

spring security 구현중,, jsp로 가져오기 전단계까지 완료,, 제선이 합치기 전

---

src/main/java/com/spring/itjunior/config/SecurityConfig.java
src/main/java/com/spring/itjunior/service/MemberServiceImpl.java

spring security 구현중,, jsp로 가져오기 전단계까지 완료,, 금요일 통합 머지

---

src/main/java/com/spring/itjunior/controller/FreeBoardController.java
src/main/java/com/spring/itjunior/controller/ReplyController.java
src/main/java/com/spring/itjunior/domain/Reply.java
src/main/java/com/spring/itjunior/dto/ReplyDto.java
src/main/java/com/spring/itjunior/mapper/FreeBoardMapper.java
src/main/java/com/spring/itjunior/mapper/ReplyMapper.java
src/main/java/com/spring/itjunior/service/FreeBoardService.java
src/main/java/com/spring/itjunior/service/ReplyService.java
src/main/resources/mapper/FreeBoardMapper.xml
src/main/resources/mapper/MemberMapper.xml
src/main/resources/mapper/ReplyMapper.xml
src/main/resources/static/css/board.css
src/main/webapp/WEB-INF/views/freeBoard/freeBoardDetail.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp

취업토론 게시판 정리, 댓글

---

build.gradle
src/main/java/com/spring/itjunior/config/SecurityConfig.java
src/main/java/com/spring/itjunior/controller/MemberApiController.java
src/main/java/com/spring/itjunior/controller/MemberController.java
src/main/java/com/spring/itjunior/exception/CommonExceptionHandler.java
src/main/java/com/spring/itjunior/mapper/MemberMapper.java
src/main/java/com/spring/itjunior/service/MemberService.java
src/main/java/com/spring/itjunior/service/MemberServiceImpl.java
src/main/resources/application.yml
src/main/resources/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/member/findIdForm.jsp
src/main/webapp/WEB-INF/views/member/updateForm.jsp
src/main/webapp/WEB-INF/views/mypage/passwordCheckForm.jsp

spring security 구현중,, 아이디찾기 완료,, 비밀번호 찾기 구현,,그 후 바로 ouath2 일요일 머지

---

src/main/java/com/spring/itjunior/controller/ReplyController.java
src/main/java/com/spring/itjunior/mapper/ReplyMapper.java
src/main/java/com/spring/itjunior/service/ReplyService.java
src/main/resources/mapper/ReplyMapper.xml
src/main/resources/static/css/board.css
src/main/webapp/WEB-INF/views/freeBoard/freeBoardDetail.jsp

댓글리스트 , 부모댓글 추가 , 대댓글 추가 구현중

---

src/main/java/com/spring/itjunior/controller/FreeBoardController.java
src/main/java/com/spring/itjunior/controller/ReplyController.java
src/main/java/com/spring/itjunior/domain/Reply.java
src/main/java/com/spring/itjunior/mapper/ReplyMapper.java
src/main/java/com/spring/itjunior/service/ReplyService.java
src/main/resources/mapper/ReplyMapper.xml
src/main/resources/static/css/board.css
src/main/webapp/WEB-INF/views/freeBoard/freeBoardDetail.jsp

댓글 좋아요 싫어요

---

src/main/webapp/WEB-INF/views/freeBoard/freeBoardDetail.jsp

댓글 좋아요 싫어요 완료

---

src/main/java/com/spring/itjunior/controller/MemberController.java
src/main/webapp/WEB-INF/views/member/updateForm.jsp

spring security 구현중,, 아이디찾기 완료,, 비밀번호 찾기 구현,,그 후 바로 ouath2 하기전에 링크 설정하기

---

.gitignore
src/main/java/com/spring/itjunior/config/SecurityConfig.java
src/main/java/com/spring/itjunior/config/auth/PrincipalDetails.java
src/main/java/com/spring/itjunior/config/oauth/PrincipalOauth2UserService.java
src/main/java/com/spring/itjunior/controller/HomeController.java
src/main/java/com/spring/itjunior/controller/MemberController.java
src/main/java/com/spring/itjunior/domain/Member.java
src/main/java/com/spring/itjunior/dto/JoinDto.java
src/main/java/com/spring/itjunior/dto/UpdateMemberDto.java
src/main/java/com/spring/itjunior/service/MemberServiceImpl.java
src/main/resources/application.yml
src/main/resources/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/alert.jsp
src/main/webapp/WEB-INF/views/home.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp
src/main/webapp/WEB-INF/views/member/loginForm.jsp
src/main/webapp/WEB-INF/views/member/updateForm.jsp
src/main/webapp/WEB-INF/views/mypage/mypage.jsp
src/main/webapp/WEB-INF/views/mypage/passwordCheckForm.jsp
src/test/java/com/spring/itjunior/BCcyptEncoder/EncoderTests.java
src/test/java/com/spring/itjunior/member/MemberTests.java

Oauthlogin2

---

src/main/java/com/spring/itjunior/config/oauth/PrincipalOauth2UserService.java
src/main/java/com/spring/itjunior/config/oauth/provider/GoogleUserInfo.java
src/main/java/com/spring/itjunior/config/oauth/provider/NaverUserInfo.java
src/main/java/com/spring/itjunior/config/oauth/provider/OAuth2UserInfo.java
src/main/java/com/spring/itjunior/controller/HomeController.java
src/main/java/com/spring/itjunior/controller/MemberController.java
src/main/java/com/spring/itjunior/domain/Member.java
src/main/java/com/spring/itjunior/dto/UpdateMemberDto.java
src/main/java/com/spring/itjunior/service/MemberServiceImpl.java
src/main/resources/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/member/loginForm.jsp

spring security naver 로그인 완료 수진 짱

---

src/main/java/com/spring/itjunior/controller/FreeBoardController.java
src/main/java/com/spring/itjunior/dto/PageDto.java
src/main/java/com/spring/itjunior/paging/Criteria.java
src/main/resources/mapper/FreeBoardMapper.xml
src/main/webapp/WEB-INF/views/freeBoard/freeBoardForm.jsp
src/main/webapp/WEB-INF/views/freeBoard/freeBoardList.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp

페이징 카테고리 , 게시물 개수

---

src/main/java/com/spring/itjunior/controller/FreeBoardController.java
src/main/java/com/spring/itjunior/controller/QnaBoardController.java
src/main/java/com/spring/itjunior/domain/FreeBoard.java
src/main/java/com/spring/itjunior/mapper/QnaBoardMapper.java
src/main/java/com/spring/itjunior/service/QnaBoardService.java
src/main/resources/mapper/FreeBoardMapper.xml
src/main/resources/mapper/QnaBoardMapper.xml
src/main/webapp/WEB-INF/views/freeBoard/freeBoardForm.jsp
src/main/webapp/WEB-INF/views/qnaBoard/qnaBoardDetail.jsp
src/main/webapp/WEB-INF/views/qnaBoard/qnaBoardList.jsp

취업토론 게시판 공지사항쓰기, 큐앤에이 관리자 답변달기

취업토론 게시판 공지사항쓰기, 큐앤에이 관리자 답변달기

---

src/main/resources/mapper/QnaBoardMapper.xml

큐앤에이 검색 수정

---

src/main/java/com/spring/itjunior/controller/FreeBoardController.java
src/main/java/com/spring/itjunior/controller/QnaBoardController.java
src/main/java/com/spring/itjunior/controller/ReplyController.java
src/main/java/com/spring/itjunior/domain/Answer.java
src/main/java/com/spring/itjunior/domain/FreeBoard.java
src/main/java/com/spring/itjunior/domain/FreeLike.java
src/main/java/com/spring/itjunior/domain/QnaBoard.java
src/main/java/com/spring/itjunior/dto/BoardDto.java
src/main/java/com/spring/itjunior/dto/QnaDto.java
src/main/java/com/spring/itjunior/service/FreeBoardService.java
src/main/java/com/spring/itjunior/service/PagingService.java
src/test/java/com/spring/itjunior/service/FreeBoardServiceTest.java

freeboard, qna Controller 정리

---

src/main/webapp/WEB-INF/views/job/jobList.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp

날짜변환 필요하신 분 jobList.jsp가서 확인하세용

채용리스트 파싱 성공,, 날짜변환까지 성공,,

---

src/main/webapp/WEB-INF/views/freeBoard/freeBoardDetail.jsp
src/main/webapp/WEB-INF/views/job/jobList.jsp

스크랩 로직 거의 완료

---

src/main/java/com/spring/itjunior/config/SecurityConfig.java
src/main/java/com/spring/itjunior/controller/HomeController.java
src/main/java/com/spring/itjunior/controller/RecruitController.java
src/main/java/com/spring/itjunior/mapper/RecruitMapper.java
src/main/resources/mapper/RecruitMapper.xml
src/main/webapp/WEB-INF/views/member/loginForm.jsp
src/main/webapp/WEB-INF/views/mypage/mypage.jsp

아이디저장 구현 완료,, 마이페이지 스크랩확인 기능 구현중,,

---

src/main/java/com/spring/itjunior/domain/RecruitDTO.java
src/main/resources/mapper/RecruitMapper.xml
src/main/webapp/WEB-INF/views/mypage/jobScrapList.jsp
src/main/webapp/WEB-INF/views/mypage/mypage.jsp

mypage 스크랩 보기 구현중,, 날짜정렬,진행중/마감 구분하기,,

---

src/main/java/com/spring/itjunior/controller/RecruitController.java
src/main/java/com/spring/itjunior/mapper/RecruitMapper.java
src/main/java/com/spring/itjunior/service/PagingService.java
src/main/java/com/spring/itjunior/service/RecruitService.java
src/main/java/com/spring/itjunior/service/RecruitServiceImpl.java
src/main/resources/mapper/RecruitMapper.xml
src/main/webapp/WEB-INF/views/mypage/jobScrapList.jsp

mypage 스크랩 보기 구현완료,, aws 배포 준비하기,,

---

src/main/java/com/spring/itjunior/config/auth/PrincipalDetails.java
src/main/java/com/spring/itjunior/config/auth/PrincipalDetailsService.java
src/main/java/com/spring/itjunior/config/oauth/PrincipalOauth2UserService.java
src/main/java/com/spring/itjunior/controller/MemberController.java
src/main/resources/mapper/MemberMapper.xml
src/main/resources/mapper/RecruitMapper.xml

aws 배포 준비하기,, 메서드 주석 달기
